culture/review_culture.md

Lately we've been discussing how cultivating [review culture][1]
across SourceCred will help us stay aligned as we grow our community. In
particular, I think we should start producing shared "docs artifacts"
that we've reviewed and we stand behind as a community. By "docs
artifacts" I mean both things like user guides, and also community
touchstones.
So, to kick things off, I wrote this guide on review culture, which I
hope will be one of the first docs artifacts. Please review it and let
me know what you think. :)
[1]: https://discourse.sourcecred.io/t/spontanious-community-call/543

Add an initial guide on review culture

---

culture/review_culture.md

Summary:
When a reviewer approves a change while simultaneously leaving small
comments, the change author can merge the change after addressing those
comments, without needing to wait for explicit re-approval from the
reviewer. We call this practice "nit-and-approve". Used appropriately,
it saves time and streamlines the review process.
wchargin-branch: nit-and-approve

review: encourage nit-and-approve

---

culture/review_culture.md

This is hard to articulate, but I think important to add (it's hit me several times in various open source communities, and it helps to have awareness for it). Basically:
- people vary in how they communicate.
- if expectations are not lined up (for example, I expect criticism wrapped in complements and an interaction is more straight forward) this can lead to hurt feelings or conflict
- we have to encourage folks to be aware of the differences, so if a conflict arises, they can either realize "It's not me, this person just communicates more straight forward" or "This isn't how I want these interactions to go, I want to open a dialogue about it."
it's a hard thing to write up, because there isn't a single right way or suggestion to make for how to best communicate. But I do think entering …

Adding notes on communication differences to review culture document

---

docusaurus.config.js
src/pages/discord.js

Closes #61
Fixed some mis-configured links in the navbar and added the Discord redirect back so people who visit sourcecred.io/discord will get sent to our Discord server

Fix broken links and add Discord redirect

---

docs/setup/installation.md

This summarizes the main instructions from the current [README] and adds
more info about Docker tags.
This document is deliberately kept concise, as it's very developer focused
and likely to be replaced soon with easier options. However these are the
only officially released install options right now.
I'm imagining these instructions might move back to the code repository
as building / running instructions, while we recommend an easier approach
to deploy a SourceCred instance in these documents instead.
[README]: https://github.com/sourcecred/sourcecred/blob/f557af90200c80b45aee2351f29c832105acccc0/README.md

Install instructions, first draft

---

blog/2020-05-11-version-0.5.0-released.md

Depends on: #71
Fixes: #73 
Taking a stab at blogging about the v0.5.0 release: https://github.com/sourcecred/sourcecred/issues/1679.
I've written this in a more personal rather than neutral tone. As that means opinions included, I've not used "SourceCred" as the author but put this under my own name.
The release notes here: https://github.com/sourcecred/sourcecred/releases/tag/v0.5.0
Are what I would likely have copied if asked for a more neutral SourceCred message.
What do you think of this approach, like the personal notes? Think we should have an official SourceCred post instead? _Let me know in the comments below, hit like and subscribe, find me on Patreon, buy a mug from the store, etc. you know how it works._

Blog: Version 0.5.0 released

---

blog/2020-05-11-version-0.5.0-released.md
docs/contributing/get-an-ambassador.md
docusaurus.config.js
src/pages/discord.js

This updates the Discord invite link so that it now drops people in the
start-here channel rather than the general channel. I've also updated
existing hardcoded references to old invites to all point to the
redirect, so that we can continue to update invite links in the future.
Possible TODO: if we find that the redirect adds an extra annoying step
for the user, we could always make a variable for the discord invite and
depend on it via code. But for now I think this is fine.
Test plan: In the CI preview, test out `https://sourcecred.io/discord`.

Update Discord invite link

---

docs/contributing/get-involved.md

Our thinking around Ambassadorship is changing, so I've replaced section 5 of this doc which explains how to get an ambassador for yourself with information about how to attend the "Jams" we've started doing. 
I also updated a few channel names that have changed in our Discord.

Replace "Get An Ambassador" section with "Attend a Jam"

---

docs/contributing/get-involved.md
src/pages/calendar.js

Navigating to `https://sourcecred.io/calendar` should now direct one to
the SourceCred Google Calendar.
I also modified all existing links to redirect here, so that we can
atomically update the calendar if needs be.
Test plan: Try the url, try some existing links.

Add the calendar redirect

---

docusaurus.config.js

This ensures that the website has darkmode enabled by default, which is more on-brand for SC.
Merging this into the branch for updating Docusaurus (PR #96) since the current version we have doesn't have this feature.

Enable darkmode by default

---

docusaurus.config.js
package.json
src/pages/index.js
yarn.lock

The latest version of Docusaurus includes some nice UX improvements and bug fixes.
See full changelog here: https://github.com/facebook/docusaurus/releases
Also fixed the Links on homepage to prevent re-loading the whole site and preload the content to make everything more snappy.
Changes seemed too small to split across multiple PRs, but happy to do that as well if each of these commits can be considered PR worthy on their own

Update Docusaurus to Latest Version + Improve Links on Homepage

---

blog/2020-04-08-coming-soon.md
blog/2020-05-11-version-0.5.0-released.md
static/admin/config.yml
static/admin/index.html

This configures Netlify CMS to allow people to create and edit pages in our docs repo without having to know how to use git. Right now its only setup for blog posts just to see if we can get it working properly.
- The config can be found in `static/admin/config.yml`, more info on available options can be found [here](https://www.netlifycms.org/docs/configuration-options/).
- You can access the admin UI by appending `/admin` to the URL. [Deploy preview of the Admin UI](https://deploy-preview-98--priceless-morse-4119fb.netlify.app/admin)
- The reason its going to be a bit trickier for docs is the sidebars.js file that specifies what pages are visible and in what order in the side navigation. One solution to this would be to have a script that can autogenerate the sidebars.js file before the …

Setup Netlify CMS

---

docs/intro/resources.md
docusaurus.config.js
static/admin/config.yml

This will allow us to write/edit docs pages through a visual CMS accessible at [sourcecred.io/admin](https://sourcecred.io/admin). One shortcoming right now is the inability to edit the sidebar from the CMS interface, that will require some custom code / widgets to link the files and generate the correct JSON format. For now, we can just edit the sidebar in code as needed. A lot of the docs have placeholder TODO files, so it shouldn't be too big of a deal. 
Test Plan: Go to the admin page and see if all the current docs are visible there and that creating a new doc in a certain section creates the file in the correct folder.

Setup Editor Interface for Docs Pages

---

docs/setup/plugins/discourse.md

Created a rough first draft of the Discourse plugin page. Mostly porting content from the existing [Discourse docs](https://github.com/sourcecred/docs/blob/master/docs/setup/plugins/discourse.md). Using the GitHub plugin page as a template, which I think worked well. 
I think I was able to come up with decent definitions for the nodes and edges, but they definitely need a thorough review and probably some tweaking. Left comments with questions throughout in format {SB: my Q). Also raising the issue of figuring out where we want more detailed instructions on configuring and running the plugin...

1st draft Discourse plugin page

---

docs/setup/installation.md

This PR updates the installation page to reflect the latest changes for beta 1 release.
Changes:
- Added example instance installation instructions
- Removed some configuration details (which will go in the new Configuration page)
- Minor rewording/formatting in Development Setup section
The Development Setup section could definitely use a review. Hasn't been changed in 3 months .

Update Installation page

---

README.md
docs/FAQ.md
docs/best-resources-for-new-contributors.md

Turns out the following comment syntax doesn't work with docasaurus:
> `[comment]: <> (This is a comment, it will not be included)`
Therefore we switch to:
> `[//]: # (This is a comment, it will not be included)`
This unbreaks the build. Yay!

Fixup comments

---

docs/beta/our-platforms.md

-changed word choice
- uppercased "Minted"
- deleted the Using Shortcuts to Navigate Roam section, as we won't be organizing Roam before the beta release

Bex's beta docs review

---

docs/beta/cred.md
docs/beta/grain.md

Per request of @Bex2594. Most fixes straightforward. Some notes:
- The heading “Grain Distribution Policies” needs to be an h3 (`###`),
not an h4 (`####`), because it’s nested under an h2 (`##`). This is
important for accessibility tools, like screen readers.
- I’ve updated link text to stand by itself, which is [also important
for accessibility tools][wcag-link-text].
- I’ve restructured the “How much is grain worth?” item to discuss the
general case first and foremost, mentioning SourceCred’s own grain
details as secondary.
- The spelling _transferable_ (one *r*) looks more correct to my eyes,
to my spell checker, and to [historical usage][ngram-transferable].
[ngram-transferable]: https://books.google.com/ngrams/graph?content=transferable%2Ctransferrable&year_start=1800&year_end=2000 …

docs: freshen `cred.md` and `grain.md`

---

docusaurus.config.js

"Chat" "Forum" and "Our Cred" were not very clear labels to newcomers, since we talk predominantly about our Discord, our Discourse, and our Cred Explorer.

Update website footer labels

---

docs/beta/plugins/discord.md

Numbers 6 & 7 weren't showing up as headings and therefore weren't showing up in the intra-doc navigation. This should fix that.

Fix 6&7 so they are formatted properly

---

docs/beta/grain.md

Adding a link to the grain distribution config example in the README provides a nice flow from conceptual to "practical" and makes it easier for users to find what they're looking for. Pointing to the example config in the template instance also decreases maintenance lift, since we only need to maintain one example.

Add grain distribution configuration link to template instance

---

docusaurus.config.js
src/css/custom.css

A few small tweaks to the announcement bar on the site so it fits a bit nicer with our branding and is a bit more legible.  Note that the bar does not stick to the top of the browser like the nav bar does, so the larger size shouldn't be an issue of taking up too much screen space. 
**View on desktop:**
**View on mobile:**

Small design tweaks to announcement bar
