sourcecred/docs

culture/review_culture.md

review: merge nit-and-approve section into master

---

community/concepts/bikeshedding.md

Last one! :tada: This will add the bikeshedding concept page.
Signed-off-by: vsoch <vsochat@stanford.edu>

[glossary] adding draft of concept: bikeshedding

---

community/concepts/champion.md

This will add "champion" to be one of the concepts to be under review!
Signed-off-by: vsoch <vsochat@stanford.edu>

[glossary] adding draft of concept: champion

---

community/concepts/deep-then-wide.md

This is a pull request to replace #18 - the branch has been moved to the sourcecred organization so @decentralion can easily add their wisdom. Take it away, @decentralion! I'll have the other pull request (for a different concept) open shortly. When this is merged given the shared commits, it should close #18 too.
Signed-off-by: vsoch <vsochat@stanford.edu>

[glossary] adding draft of concept: deep then wide

---

community/concepts/grain.md

Based on sourcecred/docs#23, but updated with our latest thinking on
grain.

Add a glossary concept for grain

---

docusaurus.config.js
src/pages/styles.module.css

Added a link to the cred graph in the nav bar (thx @Beanow and @decentralion for deploying it on a separate subdomain).
Also a minor layout/styling fix for the homepage, previously was cutting off logo and causing text to wrap on mobile devices.

Add Link To Prototype (feat. styling fix)

---

docs/concepts/initiatives.md

Only making sure there's something here. Feel free to edit as you see fit. Unless you'd like me to specifically answer something, I think it's probably better I move on to making sure technical details also exist :]

Initiatives concept, first stab

---

docs/setup/plugins/initiatives.md

I've included Status and Caveats as well as the setup here. Assuming the audience for the setup guide is the same as for the caveats.
Not yet including User guide or Advanced topics to not make this commit too large to review.
As this guide is for [stage 2](https://roamresearch.com/#/app/SourceCred/page/MJtfaaIhK), I'm assuming it would be good to give this a high-level review and refine this later.
If you think I'm on the right track here, I'll follow up with the User guide. The Advanced topics is probably something to come back to later.

Initiatives setup, first draft

---

docs/setup/plugins/discourse.md

Fairly similar format to the initiatives setup page.
I've included Status and Caveats as well as the setup here. Assuming the audience for the setup guide is the same as for the caveats. I know we're considering moving that, but for now wanted to prioritize this document existing at all :]

Discourse setup, first draft

---

docs/contributing/get-involved.md

I did a raw copy of the markdown from this post: https://discourse.sourcecred.io/t/joining-the-sourcecred-community-a-masterguide/728
We will want to check links, maybe make some tweaks, but getting started by directly copying @LexBirdie's post.
Paired with: @LexBirdie

Port LB's Community Masterguide from Discourse

---

docs/concepts/grain.md

(docfix) fix link on grain.md

---

docs/guides/earning-cred.md

my first pull requests.... and largely drafted from @decentralion and @Bex2594 's post in discourse

first draft _ earning cred

---

docs/concepts/champion.md

fixed typo

---

docs/FAQ.md

Wrote a basic FAQ for the beta milestone docs. Can probably add a lot more in here, but I imagine a lot of stuff will get covered in the other docs as well, so focused this mostly on things outside of explaining cred/grain and how it works.
List of Questions:
- Isn't SourceCred gameable? How do you prevent Sybil attacks?
- What platforms does SourceCred currently support?
- How can you track contributions that don't take place on the supported platforms?
- Should I use SourceCred for my Community?
- How is SourceCred funded and how will it be sustainable long term?
If anyone has suggestions for other questions we should answer here let me know!

Write initial FAQ Doc

---

docs/guides/flowing-cred.md

This is a document that pulls from the "How to Earn Cred" guide and "Cred" concept on the sourcecred.io page. The docs team has expressed wanting a short list of docs created for the Beta release, as too many could be overwhelming or difficult to understand. I have merged, edited and added to the docs we've already worked on so that all information is covered and have made sure the tone is consistent throughout the document.

How Cred Works.md

---

docusaurus.config.js
package.json
yarn.lock

This sets up local search functionality using Lunr.js via the following plugin: https://github.com/lelouch77/docusaurus-lunr-search
Note that the search wont work for local changes since it only generates the search index when doing the production build.
The components are based on the Algolia plugin, so there's a bunch of references to Algolia in the generated code, but its not actually using Algolia.

Setup Search Functionality

---

docs/setup-guide.md

Took a first stab at writing the setup guide, as agreed during our last docs meeting. I made a point of orienting the reader before going straight into the gory details. Hat tip to https://github.com/sourcecred/docs/pull/115 which I used as a reference while writing this.

First draft of the setup guide

---

docs/beta/grain.md

The GitHub reorg deleted my version of the document, as well as Joie's revision. This is the version I originally authored for the beta docs

How Grain Works

---

docs/beta/our-calls.md

Bex's review of Our Calls

---

docs/beta/our-platforms.md

capitalized Cred and Mint, fixed typos and grammar

Bex's review of Our Platforms

---

docs/beta/introduction.md

Bex's review of Introduction

---

.github/workflows/prettier.yml
package.json
yarn.lock

This way we gain control over which version of prettier is used. It's
also simplier.
Paired with: @wchargin

Switch to a home-rolled prettier action

---

docs/beta/best-resources-for-new-contributors.md

- slight word chioce changes
- removed Extra Content section, as it would involve linking to docs that haven't been reviewed, have little relevance comparitively to the core beta docs, and may be outdated

Bex's beta docs edit

---

docs/beta/our-calls.md

-slight word choice and punctuation changes

Bex's beta docs review

---

docs/beta/introduction.md

Bex's beta docs reivew

---

docs/beta/cred.md

Rereviewed for:
- accessible and consistent language
- typos/grammar
- understandable concepts
-any conceptual gaps
- Cred/Grain capitalization and mint/minting lowercase
Changed:
-word choice and grammar

Bex's final edit of How Cred Works

---

docs/beta/cred.md
docs/beta/grain.md

changed the description for minting Cred, as @s-ben suggested on the FAQ discourse post.

changed Cred minting description

---

docs/beta/grain.md

-took out section on Grain distribution specific to SourceCred instance
-fixed broken link for minting
-changed harvest to grain distribution
-continuity fixes
-grammar fixes

final update on How Grain Works

---

sidebars.js

Revert "Update sidebars.js"

---

docs/beta/cred.md

This is my review/rewrite of the Cred overview document. I tried to hit
all the same points from the original doc, but in a way that was a bit
more precise in how the algorithm is described.

Rewrite of the Cred overview doc

---

docs/beta/introduction.md

-removed values section
-small nit edits
-removed boosting

final review of Intro to SourceCred

---

docs/beta/plugins/discord.md

- fixed typo
- added tech support Discord channel

Final Review of Discord Plugin

---

docs/beta/plugins/github.md

Final Review of GitHub Plugin

---

docs/beta/plugins/discord.md
docs/beta/plugins/discourse.md
docs/beta/plugins/initiatives.md

Removed placeholder comments (TODO, EXAMPLE HERE, etc.), made minor formatting changes.

Cleaned up placeholder text, minor formatting changes

---

docs/beta/setup-guide.md

- fixed broken link
- added additional resources

final review

---

docs/beta/our-platforms.md

Made mint lowercase, took out that SC emojis are worth 16x other emojis, since this will probably change in the near future, upgraded readability

Final Review Our Platforms

---

docs/beta/FAQ.md

This Pull Request changes the order of the answers in the FAQ by quite a bit, making it one designed and streamlined whole. I've also made a couple of tiny tweaks to some of the answers, added and fixed some links, and formatted the whole thing as a headings-paragraphs document instead of a nested list, so that the right column now shows a table of contents for all of the questions. 
A preview can be seen here:
https://deploy-preview-244--sourcecred.netlify.app/docs/beta/faq/
PR Automatically generated by Netlify CMS

Reorder FAQ page contents

---

docs/beta/grain.md

I've added the notes that @s-ben and @kurafire drafted,
alongside some details to help readers think about Grain
on a broad level and give an idea for what the future
may hold.

grain: add recent details + general grain info

---

docs/setup/FAQ.md

A community member is interested in helping to get a
technically-oriented FAQ for instance maintainers going! This can be
found at localhost:3000/docs/setup/FAQ when serving the instance
locally.

Add a WIP Instance Setup FAQ file

---

docs/setup/FAQ.md

Adding a few common errors, that popped up when I was setting up a sourcecred instance for the first time.

Add common errors to setup FAQ section

---

docs/setup/FAQ.md

Also cleaned up the current format and organization a bit.

Add memory related error explanation to FAQ

---

docs/beta/our-values.md
sidebars.js

Ported values [statement draft ](https://roamresearch.com/#/app/SourceCred/page/U9BJFMChG)created in Town Hall to new page.
Note: in the draft, there were link placeholders on the following text:
our shadow worklink
practice consent culturelink*.
We move at the speed of trust(link).*
Don't have those links now, so shipping without, but we can add later.

Add Our Values page

---

docs/beta/grain.md

There are 3 policies actually on the docs

Update policy to "three"

---

docs/guides/adopting.md
docs/guides/dev-env-setup.md

Just a tiny update to development environment setup guide: added s brief overview of key technologies employed and VSCode as a possible IDE can be used.

Updating development environment setup guide

---

docs/beta/cred.md
docs/beta/our-calls.md
docs/guides/dev-env-setup.md
docs/guides/opt-in-process.md

Fix: typos
